import type { ThemeDefinition, ThemeId, ThemeScope } from "./types";

// Catálogo base de temas.
// Observação: cores usam tokens existentes (gradientes utilitários) para evitar crescer o design system agora.
export const BASE_THEMES: ThemeDefinition[] = [
  // comuns
  {
    id: "natal",
    name: "Natal",
    iconName: "TreePine",
    scope: "common",
    imageKey: "natal",
    gradientClass: "bg-gradient-festive",
    description: "Magia natalina e surpresas especiais!",
    emoji: "🎄",
    enabledByDefault: true,
  },
  {
    id: "reveillon",
    name: "Réveillon",
    iconName: "PartyPopper",
    scope: "common",
    imageKey: "reveillon",
    gradientClass: "bg-gradient-festive",
    description: "Contagem regressiva para o novo ano!",
    emoji: "🥂",
    enabledByDefault: true,
  },
  {
    id: "pascoa",
    name: "Páscoa",
    iconName: "Egg",
    scope: "common",
    imageKey: "pascoa",
    gradientClass: "bg-gradient-festive",
    description: "Carinho, chocolate e mensagens especiais.",
    emoji: "🐰",
    enabledByDefault: true,
  },

  // nacionais
  {
    id: "carnaval",
    name: "Carnaval",
    iconName: "Music",
    scope: "b2c",
    imageKey: "carnaval",
    gradientClass: "bg-gradient-carnaval",
    description: "Energia, cores vibrantes e muita alegria!",
    emoji: "🎭",
    enabledByDefault: true,
  },
  {
    id: "saojoao",
    name: "São João",
    iconName: "Flame",
    scope: "b2c",
    imageKey: "saojoao",
    gradientClass: "bg-gradient-saojoao",
    description: "Arraial, forró e tradição junina!",
    emoji: "🔥",
    enabledByDefault: true,
  },
  {
    id: "independencia",
    name: "Independência",
    iconName: "Flag",
    scope: "b2c",
    imageKey: "independencia",
    gradientClass: "bg-gradient-festive",
    description: "Celebrar o Brasil com surpresas diárias.",
    emoji: "🇧🇷",
    enabledByDefault: true,
  },
  {
    id: "diadasmaes",
    name: "Dia das Mães",
    iconName: "Heart",
    scope: "b2c",
    imageKey: "diadasmaes",
    gradientClass: "bg-gradient-festive",
    description: "Mensagens e memórias para a mãe.",
    emoji: "💝",
    enabledByDefault: true,
  },
  {
    id: "diadospais",
    name: "Dia dos Pais",
    iconName: "User",
    scope: "b2c",
    imageKey: "diadospais",
    gradientClass: "bg-gradient-festive",
    description: "Gratidão e surpresas para o pai.",
    emoji: "👔",
    enabledByDefault: true,
  },
  {
    id: "diadascriancas",
    name: "Dia das Crianças",
    iconName: "Gamepad2",
    scope: "b2c",
    imageKey: "diadascriancas",
    gradientClass: "bg-gradient-carnaval",
    description: "Diversão e carinho para os pequenos.",
    emoji: "🧸",
    enabledByDefault: true,
  },

  // datas importantes
  {
    id: "aniversario",
    name: "Aniversário",
    iconName: "Cake",
    scope: "b2c",
    imageKey: "aniversario",
    gradientClass: "bg-gradient-festive",
    description: "Um presente por dia até o grande dia.",
    emoji: "🎂",
    enabledByDefault: true,
  },
  {
    id: "viagem",
    name: "Viagem",
    iconName: "Plane",
    scope: "b2c",
    imageKey: "viagem",
    gradientClass: "bg-gradient-saojoao",
    description: "Checklist e surpresas até a partida.",
    emoji: "✈️",
    enabledByDefault: true,
  },
  {
    id: "estudos",
    name: "Estudos",
    iconName: "BookOpen",
    scope: "b2c",
    imageKey: "estudos",
    gradientClass: "bg-gradient-festive",
    description: "Rotina e motivação para a prova.",
    emoji: "📚",
    enabledByDefault: true,
  },
  {
    id: "metas",
    name: "Metas",
    iconName: "Target",
    scope: "b2c",
    imageKey: "metas",
    gradientClass: "bg-gradient-carnaval",
    description: "Micro-hábitos e progresso diário.",
    emoji: "🎯",
    enabledByDefault: true,
  },
  {
    id: "custom",
    name: "Personalizado",
    iconName: "Palette",
    scope: "common",
    imageKey: "peeking",
    gradientClass: "bg-gradient-festive",
    description: "Crie o seu estilo único!",
    emoji: "🎨",
    enabledByDefault: true,
  },

  // relacionamento
  {
    id: "namoro",
    name: "Amor & Romance",
    iconName: "Heart",
    scope: "b2c",
    imageKey: "namoro",
    gradientClass: "bg-gradient-romance",
    description: "Para celebrar o amor todos os dias.",
    emoji: "❤️",
    enabledByDefault: true,
  },
  {
    id: "noivado",
    name: "Eternamente Juntos",
    iconName: "Sparkles",
    scope: "b2c",
    imageKey: "noivado",
    gradientClass: "bg-gradient-romance",
    description: "Momentos especiais e memórias juntos.",
    emoji: "💍",
    enabledByDefault: true,
  },
  {
    id: "casamento",
    name: "Nossa União",
    iconName: "Church",
    scope: "b2c",
    imageKey: "casamento",
    gradientClass: "bg-gradient-wedding",
    description: "Comemorando nossa história de amor.",
    emoji: "👰",
    enabledByDefault: true,
  },
  {
    id: "bodas",
    name: "Bodas",
    iconName: "Wine",
    scope: "b2c",
    imageKey: "bodas",
    gradientClass: "bg-gradient-romance",
    description: "Celebre etapas e conquistas juntos.",
    emoji: "🥂",
    enabledByDefault: true,
  },

  // b2b
  {
    id: "campanha_lancamento",
    name: "Lançamento",
    iconName: "Rocket",
    scope: "b2b",
    imageKey: "peeking",
    gradientClass: "bg-gradient-festive",
    description: "Sequência de conteúdo para lançamento.",
    enabledByDefault: true,
  },
  {
    id: "campanha_promocao",
    name: "Promoção",
    iconName: "Tag",
    scope: "b2b",
    imageKey: "peeking",
    gradientClass: "bg-gradient-carnaval",
    description: "Ofertas e CTAs diários para conversão.",
    enabledByDefault: true,
  },
  {
    id: "rh_onboarding",
    name: "Onboarding RH",
    iconName: "Monitor",
    scope: "b2b",
    imageKey: "peeking",
    gradientClass: "bg-gradient-saojoao",
    description: "Boas-vindas e rotinas para novos colaboradores.",
    enabledByDefault: true,
  },
  {
    id: "endomarketing",
    name: "Endomarketing",
    iconName: "Megaphone",
    scope: "b2b",
    imageKey: "peeking",
    gradientClass: "bg-gradient-festive",
    description: "Cultura, comunicados e engajamento interno.",
    enabledByDefault: true,
  },
  {
    id: "comunidade",
    name: "Comunidade",
    iconName: "Users",
    scope: "b2b",
    imageKey: "peeking",
    gradientClass: "bg-gradient-carnaval",
    description: "Conteúdo recorrente para membros e clientes.",
    enabledByDefault: true,
  },
  {
    id: "encontro_remoto",
    name: "Encontro do time remoto",
    iconName: "UserPlus", // Changed from twin user emoji
    scope: "b2b",
    imageKey: "peeking",
    gradientClass: "bg-gradient-saojoao",
    description: "Aquecimento, agenda e dinâmicas antes do encontro.",
    enabledByDefault: true,
  },
];

export const groupLabel: Record<ThemeScope, string> = {
  common: "Comuns",
  b2c: "B2C",
  b2b: "B2B",
};

export const getThemeDefinition = (themes: ThemeDefinition[], id: ThemeId) =>
  themes.find((t) => t.id === id) ?? null;
