name: fresta_flutter
description: Fresta B2C mobile app (Flutter MVP).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/fresta_icon_final_concept_1_flat_1772239935761.png"
  adaptive_icon_background: "#0F1A16"
  adaptive_icon_foreground: "assets/images/fresta_icon_final_concept_1_flat_1772239935761.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0F1A16"
  image: "assets/images/fresta_splash_screen_concept_1_1772239948416.png"
  android_12:
    color: "#0F1A16"
    image: "assets/images/fresta_icon_final_concept_1_flat_1772239935761.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/themes/
    - assets/images/
